apiVersion: v1
#apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: dropcapabilities
spec:
  privileged: false
  requiredDropCapabilities: ["NET_BIND_SERVICE", "SETUID", "SETGID"]
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
    - '*'
  hostNetwork: true
  hostPorts:
    - min: 1
      max: 65536
