apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: chef-server
spec:
  privileged: false  # Don't allow privileged pods!
  # The rest fills in some required fields.
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 1
    max: 65536
---
apiVersion: v1
kind: Pod
metadata:
  name: chef-server
spec:
  securityContext:
    allowPrivilegeEscalation: false
    drop: ["NET_BIND_SERVICE", "SETUID", "SETGID"]
    runAsUser: 42
    fsGroup: 42
  containers:
  - name: postgresql
    image: gcr.io/habitat-kubernetes-playland/postgresql:latest
    # command: ["sh", "-c", "chown -R 42:42 /hab/svc/postgresql/data"]
    resources:
      requests:
      cpu: 100m
      memory: 100Mi
    env:
    - name: HAB_POSTGRESQL
    ports:
    - containerPort: 5432
      name: postgresql
    volumeMounts:
    - name: postgresql-persistent-storage
      mountPath: /hab/svc/postgresql/data
   volumes:
   - name: postgresql-persistent-storage
     gcePersistentDisk:
       pdName: postgresql-disk
       fsType: ext4
