apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: chef-server
    tier: backend
    role: master
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: chef-server
    tier: backend
    role: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: postgresql
        image: gcr.io/habitat-kubernetes-playland/postgresql:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5432
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: chef-server-postgresql-fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zones: us-central1-b
